version: "3.3"

services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    # labels:
    #   - "traefik.enable=false"
    environment:
       - "TZ=Asia/Jakarta"
    ports:
      - 80:80
      - 443:443
      - 2000:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./log:/var/log/traefik
    networks:
      - proxy

networks:
  proxy:
    external:
      name: web_proxy
