version: "3.3"

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    environment:
       - "TZ=Asia/Jakarta"
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.doscom.org`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=traefikauth"
      - "traefik.http.middlewares.traefikauth.basicauth.usersfile=/etc/traefik/auth"
    ports:
      - 8000:80
      - 4433:443
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config:/etc/traefik
      - ./log:/var/log/traefik
    networks:
      - proxy

networks:
  proxy:
    external:
      name: link-utama
