[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "proxy"

##Entrypoint Web
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web-secure]
    address = ":443"

##Enable LetsEncrypt
[certificatesResolvers.traefik.acme]
  email = "yusufsanjaya@gmail.com"
  storage = "acme.json"
  [certificatesResolvers.traefik.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

##Dashboard Traefik
[api]
  dashboard = true

##Ping Health Check
[ping]

##Metrics Traefik
[metrics]
  [metrics.prometheus]

##Log Traefik
[log]
  filepath = "/var/log/traefik/traefik.log"
  format = "json"